name: limon_pay
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  permission_handler: ^11.3.1
  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.11.0+2
  flutter_nfc_kit: ^3.5.2
  hex: ^0.2.0

  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  get_it: 8.0.3
  get: ^4.6.6
  logger: ^2.5.0
  nfc_manager: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/inter_regular.ttf
          weight: 400
        - asset: assets/font/inter_medium.ttf
          weight: 500
        - asset: assets/font/inter_bold.ttf
          weight: 700
